### ISSUE TITLE
Starting the RxJS docs initiative

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs-docs#4]
Hi everyone!

Here is an update -
- If you have emailed me (tracy@thisdot.co) about your desire to contribute, I have you on a list and will add you to meetings, etc. If you have not, then I have no way of communicating with you effectively. :) 

## TODO

- [x] This repo was created (woot!)
- [x] Initial Angular site setup for the RxJS docs 
- [x] Brian Troncone will be adding operator descriptions and working on the operators component based off of his already awesome work.
- [ ] Ashwin creating issues on the RxJS repo for contributing to these docs and the action items needed before October 16th.
- [ ] On October 16th, we will have a kick off meeting that all who have emailed me will be invited to to get things going!
- [ ] After that, yolo! :)

**Comment by ladyleet** [comment]
@tracyalison11 @rhgeek @btroncone FYI // @benlesh @kwonoj @jayphelps

**Comment by ladyleet** [comment]
Feel free to comment on this with ideas/suggestions to enhance our docs initiative.

**Comment by ladyleet** [comment]
@rhgeek @tracyallison11 feel free to document what you've been doing here or the plan to keep folks in the know of progress!

**Comment by feloy** [comment]
It would be interesting to configure server-side rendering, so one can get a static version of the documentation.

**Comment by inf3cti0n95** [comment]
@ladyleet How about A Progressive Web App? 

People would be able to browse docs offline :), A Nice read while traveling

**Comment by ladyleet** [comment]
@inf3cti0n95 that sounds like a great idea! optimizing for this and converting the site to that sounds perf.

**Comment by ladyleet** [comment]
@feloy agreed! that would be lovely too! i love these ideas.

**Comment by feloy** [comment]
What about creating a personalized Schematics collection so one can easily add a new rxjs operator? 

ng generate rx-operator pluck

**Comment by ladyleet** [comment]
@feloy that question will have to be bikeshedded by @benlesh and @kwonoj

**Comment by btroncone** [comment]
@inf3cti0n95 I will convert to a PWA in an early PR. 👍🏻 @ladyleet

**Comment by ladyleet** [comment]
@btroncone yeah baby!

**Comment by inf3cti0n95** [comment]
@btroncone I am in for PWA, I'll tag along 😉

**Comment by ladyleet** [comment]
@feloy omg let's do this pls.

**Comment by ladyleet** [comment]
@inf3cti0n95 https://github.com/ReactiveX/rxjs-docs/pull/5 PWA awesomeness from @btroncone

**Comment by ladyleet** [comment]
just created a bunch of issues for translating the docs.

**Comment by RHGeek** [comment]
For creating issues related to the operators that need added, we've been compiling a list of what is missing. We'll then be adding issues for each of these, possibly multiple for the different pieces that are needed to fully document each (i.e. description, example...). 

Here is the current working list

- Ajax
   - get
   - post
   - delete
   - put
   - patch
   - getJSON
- distinctUntilChanged
- finally
- forkJoin
- if
- let
- publishBehavior
- publishLast
- publishReplay
- shareReplay
- skipLast
- Subject.create
- Timeinterval
- timeout
- timeoutWith
- timestamp
- toArray
- zipAll
- zipProto

Other Updates Needed
- installation guide on http://reactivex.io/rxjs
- All of the RxJS related documentation on the ReactiveX website (not the ESDoc RxJS generated one) is out of date, referencing v4 (or an even older version) http://reactivex.io/documentation/operators.html

**Comment by ladyleet** [comment]
@RHGeek That's what I'm 🌮 ing about! 🍕  create those issues when you can! :) 🍌  waiting for these docs forever! 💯

**Comment by btroncone** [comment]
Any thoughts or ideas on the best way to maintain operator information? One of the things I like about GitBook is how easy it is for others to contribute by modifying the corresponding markdown file. How can we keep this simple for contributors to add or extend explanations and examples in the new docs?

**Comment by ladyleet** [comment]
Hey @btroncone just to get things going - @benlesh and I talked about this - why don't we just create a service with the array of data that folks can update + abstract away the array by creating methods to call the data so we can change it later. Thoughts?

**Comment by btroncone** [comment]
@ladyleet That works for me. 👍

**Comment by fredrik-lundin** [comment]
I'd love to contribute when you have more concrete issues ready to be worked on :)

**Comment by ladyleet** [comment]
@fredrik-lundin actually Issue https://github.com/ReactiveX/rxjs-docs/issues/10 and Issue https://github.com/ReactiveX/rxjs-docs/issues/14 could be worked on now! :) If you're up for it!

**Comment by feloy** [comment]
@ladyleet i've made 2 proposals yesterday about SSR and Schematics. But I'm not sure of the order of your replies...

**Comment by ladyleet** [comment]
@feloy both sound like great ideas. :) feel free to take and implement! :) i esp love the idea of schematics.

**Comment by ladyleet** [comment]
@RHGeek while y'all are doing that do you want to take the other issues related to translation? and generating issues for each individual operator there?

**Comment by feloy** [comment]
@ladyleet when I work on SSR, I would be happy to work on a travisCI (or equivalent) config to automatically generate indexable pages  and deploy them on a website.
Have you already chosen a platform to deploy the website to?

**Comment by ladyleet** [comment]
@feloy not yet :( @benlesh? Thoughts?

**Comment by kwonoj** [comment]
@ladyleet @feloy I can enable travis, but not sure about auto-deploy at this moment. probably better to discuss separately (build / test on travis first, deploy as separate topic).

**Comment by ladyleet** [comment]
@feloy we currently use github pages so will probably stay with that. thx for checking! travisCI would be perf. <3

**Comment by ladyleet** [comment]
@kwonoj agreed OJ! thx for noticing and paying attention to the progress done here. :) // @feloy

**Comment by kwonoj** [comment]
Let me try to enable travis tonight and will create separate issue for those.

**Comment by ladyleet** [comment]
@kwonoj ok thx oj! :) // @feloy

**Comment by kwonoj** [comment]
Related issue https://github.com/ReactiveX/rxjs-docs/issues/18 created, and travis is enabled for this repo.

**Comment by btroncone** [comment]
Just a quick update, I'm working on operator UI right now. I hope to have a first version available with at least a sample of operators to poke around with by the end of this weekend or early next week. I'll post as soon as it's available. 👍

**Comment by ladyleet** [comment]
@btroncone awessome!

**Comment by xtianjohns** [comment]
Hey @ladyleet do you know how/if we currently track docs usage? Is there any interest in tracking which operators get the most traffic, or monitoring how users will interact with the new docs?

**Comment by ladyleet** [comment]
@xtianjohns sure that'd be so cool!

**Comment by RHGeek** [comment]
@ladyleet sorry for the delay in getting back, but yeah, we can add translation related issues to go with all the new operators. I will search to see what issues are created for particular languages (I've seen you tag me in some), but we can also identify any more that we want to proactively.

**Comment by ladyleet** [comment]
translations - we are bikeshedding here https://github.com/ReactiveX/rxjs-docs/issues/29

**Comment by RHGeek** [comment]
I've added 3 issues as examples for how all the rest from the list can be added. Please let me know if these look ok, before the rest then get added. These would be the three "pieces" needed to complete the documentation for that operator.

https://github.com/ReactiveX/rxjs/issues/2939
https://github.com/ReactiveX/rxjs/issues/2940
https://github.com/ReactiveX/rxjs/issues/2941

**Comment by ladyleet** [comment]
@rhgeek this is perfect thanks! :)

**Comment by kwonoj** [comment]
Maybe better to create single issue for each operator, then list todo as checkboxes? (though not sure which'll be better, concerning numbers of issue might get exploded)

**Comment by ladyleet** [comment]
@kwonoj yeah but closing issues just feels so good and allows easy individual contributors to work through things easier IMO.

**Comment by kwonoj** [comment]
@ladyleet yup, that's reason I'm not suggesting to do so at this moment. Have to see for few cycles to make decision.

**Comment by RHGeek** [comment]
@kwonoj @ladyleet Yeah, that was the general idea, creating them separate to make it easier for people to contribute to a piece of the documentation. If they only feel comfortable with writing descriptions and maybe not examples, they can close that out and it might be less intimidating to contribute then if all 3 pieces were in one issue. If it does seem to be too much, we can consolidate them as well.

**Comment by GustavoCostaW** [comment]
The status in our meeting about the operators visualization, we have three options:

- rxviz
- rxmarbles
- rxfiddle


Which will we use?

**Comment by arat3091** [comment]
Guys i have a question. Cant we create the branch on github which i can checkout and do my work on it and then later create the pull request to merge to master. I see i do not have the permission to create the branch . How should we go about it ?

**Comment by xtianjohns** [comment]
Hey @arat3091, you won't be able to create a branch in _this_ repository. However, you can fork this repository and create a branch in your fork. When you feel like your work is ready, you can submit your pull request from your fork into this repo. Make sense?

**Comment by crunchie84** [comment]
Shout out to @hermanbanken - would RxFiddle be a match to render the operator visualisations?

**Comment by rgbkrk** [comment]
Well this is awesome, thanks for kicking this off!

**Comment by ladyleet** [comment]
Thx Kyle!

**Comment by michahell** [comment]
thanks guys!

**Comment by benlesh** [comment]
@ladyleet how are we doing with these bullet points?

**Comment by jonathanconway** [comment]
Hey all. I'm keen to contribute. Thinking of documenting publishReplay. Shall I create an issue?

**Comment by ladyleet** [comment]
@jonathanconway yes please do!

**Comment by ladyleet** [comment]
Closing this issue out as we have kicked off the docs! If anyone in this thread still needs help contributing you can always email me at tracy@thisdot.co and I'm happy to be of service. Or, email me so I can add you to our slack channel!

**Comment by ladyleet** [comment]
@benlesh thx ben for pinging me to close this!

**Comment by cschomer** [comment]
Hi was just wondering if StackBlitz was in talks for being used and or perhaps dynamic marbles like below (granted the marbles need an auto expanding line and perhaps using svg or canvas might be better) or is there a site that already has this?
[SB Code and Demo](https://stackblitz.com/edit/typescript-6mg2tn)
[Interval Observable Example Site](https://typescript-6mg2tn.stackblitz.io)

**Comment by ladyleet** [comment]
@cschomer yes on stackblitz!
